name: Update Image
on:
  schedule:
    - cron: '0 18 * * *' # trigger daily at 00:00 CST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Pull remote
        run: |
          git config --global user.name "TeraBaito"
          git config --global user.email "${{ secrets.EMAIL }}"
          git pull

      - name: Install modules
        run: npm i canvas axios
      
      - name: Run image updater
        run: node update.js
        env:
          CI: true
          OSU_TOKEN: ${{ secrets.OSU_TOKEN }}
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "Daily image update"
          git push